### PR TITLE
UK macro

### LINKED ISSUE #32: Add UK macroeconomic indicators
From the UK ONS. There is no API key requirement (yet).
https://developer.beta.ons.gov.uk/tour/getting-started/

Good first dataset - RPI All Items
https://www.ons.gov.uk/economy/inflationandpriceindices/timeseries/czbh/mm23

Introductory blog post:
https://digitalblog.ons.gov.uk/2017/07/13/api-an-introduction/

API address for this dataset - returns complicated JSON
https://api.ons.gov.uk/timeseries/czbh/dataset/mm23/data

### PR DESCRIPTION
**Pull request by david-houseman**
Adds two UK macroeconomic indicators. Quite similar to the US patch.

### CODE REVIEW

**Comment by sjtrny** [comment]
Looks good!

My only concern is about using urllib instead of requests. Was there any particular reason for that choice? I just noticed it's used for retrieving data from FRED too.

**Comment by david-houseman** [comment]
No particular reason :-) I am not familiar with either library, and just based the code off examples I found on the web. I'll have a look into changing both to `requests`.

**Comment by david-houseman** [comment]
Hi Stephen,

I've just updated the production server, but I'm afraid the dockerfile is not correctly picking up the new requests dependency. 
`update.sh` completes with no complaints but the updater crashes with the following error

```
# docker logs forecast_dash_updater_1
Traceback (most recent call last):
  File "update.py", line 1, in <module>
    from download import download_data
  File "/updater/download.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

The updater/requirements.txt does contain the new requests dependency:

```
# cat updater/requirements.txt
pandas
requests
rpy2
scikit-learn
statsmodels
tzlocal
```

For some reason the dockerfile is not correctly picking up the deps from `updater/requirements.txt` . I don't have any experience working with docker. Do you have any suggestions?

I have rolled back the prod server to the version-before-HEAD and restarted, which appears to be working correctly.
`# git checkout 65a3ed9fc274`

Thank you,

David

**Comment by sjtrny** [comment]
Working on it now. I realised this was going to be a problem yesterday https://github.com/sjtrny/forecast_dash/issues/38

The R and Python requirements are built into the container image. So we have to rebuild the container image when we change the requirements.

The better solution is just to check requirements at image boot time and update if necessary. For R packages though installing from source is very slow. So I'm trying to get a solution for it to install from a binary instead.

**Comment by sjtrny** [comment]
Ok the site is back up and running. I found a number of other issues along the way and fixed those too. The series from the UK should appear overnight (fingers crossed).

**Comment by david-houseman** [comment]
Hi Stephen,

Sorry to report but the production updater is missing more python dependencies:

```
# docker logs forecast_dash_updater_1 
Traceback (most recent call last):
  File "update.py", line 1, in <module>
    from download import download_data
  File "/updater/download.py", line 10, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.7/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/usr/bin/python3"
  * The NumPy version is: "1.19.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

```

The dash app is working off the old pickles (no UK).

**Comment by david-houseman** [comment]
Upgraded my local build to match that version of numpy (1.19.1), but can't reproduce the error locally.

**Comment by sjtrny** [comment]
Managed to fix the issue last night. It seemed to be caused by multiple installations of Python in the docker container.

**Comment by david-houseman** [comment]
Great work :-) . Sounds tricky.

**Pull request merged**
