### PR TITLE
All models 3

### PR DESCRIPTION
**Pull request by david-houseman**
Hi Stephen,

Here is another attempt at an 'All Models' patch. This one retains the concept of a best method for each dataset, but makes other forecasts optionally available too.

- update.py generates and stores forecasts and cross-validation (CV) scores for all available methods.
- the Series page now includes a set of radio buttons for each of the available methods. Selecting a new method updates the chart, metadata and forecast_table.
- "Auto best method" is the default radio button. It selects the model with the best CV score, same as current behaviour.
- get_thumbnail_figure() displays the best method's forecasts, same as current behaviour.
- otherwise minimal changes, to reflect the new data format.

Please let me know what you think? Any tips on coding style very welcome!

Best regards,

David

forecast_dash_model_selector

### CODE REVIEW

**Comment by sjtrny** [comment]
Hi David, I've made some changes:
- used a dropdown instead of radio items
- the name of the best model is now included in the list
- removed some of the redundant lines of code

Fullscreen_6_8_20__2_51_pm

I notice that there seems to be a problem with navigating from the stats page. I think this might have been due to one of your changes along the way, since I rolled back to #adff2e0 and the bug was there.

If you do the following:
1. Go to stats page
2. Click on a method
3. Get a blank filter filter page

The traceback that I get is

```
Traceback (most recent call last):
  File "/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/venv/lib/python3.7/site-packages/dash/dash.py", line 1031, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/venv/lib/python3.7/site-packages/dash/dash.py", line 966, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/dash/pages.py", line 122, in wrapper
    return func(**kwargs_dict)
  File "/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/dash/pages.py", line 981, in filter_results
    forecast_series_dicts, kwargs[filter_key]
  File "/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/dash/pages.py", line 831, in match_methods
    if forecast_dict["model_name"] in methods:
```

Filter

**Comment by david-houseman** [comment]
Hi Stephen -- thanks for looking into this and sorry to have introduced a new bug. My bet is that this comes from the new data format of the pickles (including all forecasts). Looking into it now.

**Comment by david-houseman** [comment]
Pushed a fix now. That stack trace doesn't appear any more and the filter seems to have the correct entries in it.

**Comment by sjtrny** [comment]
All good. Merged!

**Pull request merged**
