### PR TITLE
Print git info at the bottom of main page.

### PR DESCRIPTION
**Pull request by david-houseman**

### CODE REVIEW

**Comment by david-houseman** [comment]
I implemented this just using a system call to `git show` as I think thought it might be simpler than using gitpython.

**Comment by david-houseman** [comment]
git_info

**Comment by sjtrny** [comment]
I've taken the opportunity to convert this into part of the footer, which we should show at the bottom of every page. Taking feedback on the layout here - I'm not that excited by the way I have the "Sections" laid out.

Business_Forecast_Lab

**Review by sjtrny — COMMENTED** [review]
Overall looks good. I like the simplicity. (This is the code review - not about my visual suggestions).

**Comment by sjtrny** [comment]
New layout

Business_Forecast_Lab

**Comment by david-houseman** [comment]
This looks really good and works really well as a footer. (Sorry for my slow feedback!)

**Comment by david-houseman** [comment]
This branch works locally but fails in production due to the interaction of the docker container with the system call to `git show`

Specifically, the working dir of the dash docker container is `/dash`, according to a system call to `pwd`, from which `git` fails because

```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

This is a good example of docker isolation!

We then have in common.py `git_output = []` which is currently causing the web server to crash with an index out of range error.

**Comment by david-houseman** [comment]
I have patched master branch with some temporary values for `git_output`, so the production web server is back up (and displaying meaningless git status).

**Comment by david-houseman** [comment]
Fixed on master by 5b7c5ec1, by exporting `.git/` into the docker container as a readonly volume.

**Comment by sjtrny** [comment]
Great news! Thanks David.

**Pull request merged**
